{
 "title": "Logs Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "filter" },
   {
    "name": "log_level",
    "query": {}
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Raw logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{filename=\"/logs/bot.log\", level=\"$log_level\"} |= `$filter`"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(logger) (count_over_time({filename=\"/logs/bot.log\", level=\"$log_level\"} |= `$filter` [$__auto]))"
    }
   ]
  },
  {
   "title": "Log Level Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({filename=\"/logs/bot.log\", level=\"$log_level\"} |= `$filter` | level =~ `.+` [$__auto]))"
    }
   ]
  },
  {
   "title": "Logger Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(logger) (count_over_time({filename=\"/logs/bot.log\", level=\"$log_level\"} |= `$filter` | logger =~ `.+` [$__auto]))"
    }
   ]
  }
 ]
}